apiVersion: v1
kind: Deployment
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: config-fb
        mountPath: /var/www/html/config.php
  volumes:
    - name: config-fb
      configMap:
        name: p-fb-configmap
  restartPolicy: Never